.PHONY: all clean nompi clean-nompi debug clean-debug

all:
	make -C Release/

clean:
	make -C Release/ clean

nompi:
	make -C NoMpi/

clean-nompi:
	make -C NoMpi/ clean

debug:
	make -C Debug/

clean-debug:
	make -C Debug/ clean
